"use strict";

const state={packet:null,index:0,mode:"S0",selectedChunk:null,errors:[],warnings:[]};
const byId=id=>document.getElementById(id);
const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const current=()=>state.packet.cases[state.index];
const schema=item=>item.conceptual_schema_model;

function defaultTrace(){const item=current();byId("trace-title").textContent="Schema is recoverable";byId("trace-body").textContent=`${item.metrics.explanatory_block_count} blocks become ${item.metrics.top_level_conceptual_chunk_count} top-level units while ${item.metrics.frozen_semantic_item_count} semantic items remain explicit.`;byId("trace-list").replaceChildren();}
function selectChunk(chunk){state.selectedChunk=chunk.id;byId("trace-title").textContent=`${chunk.role.replaceAll("_"," ")} · ${chunk.label}`;byId("trace-body").textContent=`${chunk.member_blocks.length} member block${chunk.member_blocks.length===1?"":"s"} · ${chunk.semantic_support_ids.length} grounded items`;const host=byId("trace-list");host.replaceChildren();chunk.membership_audit.forEach(row=>{const heading=el("p",null,`${row.block_id} · ${row.status}`);host.append(heading);row.support.forEach(support=>{const quote=support.source_ranges?.[0]?.quote;if(quote)host.append(el("blockquote",null,quote));host.append(el("p",null,`${support.type}${support.semantic_ids?` · ${support.semantic_ids.join(", ")}`:""}${support.entity_ids?` · ${support.entity_ids.join(", ")}`:""}`));});});chunk.evidence_support.forEach(range=>{host.append(el("blockquote",null,range.quote));host.append(el("p",null,`chars ${range.start_char}–${range.end_char}`));});}
function renderS0(host,item){const prose=el("p","baseline-prose",item.views.S0.text);prose.dataset.viewText=item.views.S0.text;host.append(prose);}
function leavesFor(item,top){const children=schema(item).chunks.filter(row=>row.parent_chunk===top.id);return children.length?children:[top];}
function addChunk(host,item,chunk){const section=el("section",`chunk level-${chunk.level}`),button=el("button");button.type="button";button.dataset.chunkId=chunk.id;button.append(el("span","chunk-role",`${chunk.role.replaceAll("_"," ")} · ${chunk.member_blocks.length} block${chunk.member_blocks.length===1?"":"s"}`));button.append(el("h3",null,chunk.label));button.addEventListener("click",()=>selectChunk(chunk));section.append(button);const facts=el("ul","fact-list");item.semantic_items.filter(row=>row.assigned_chunk===chunk.id).forEach(row=>{const li=el("li",null,row.statement);li.dataset.semanticId=row.upstream_id;facts.append(li);});if(facts.children.length)section.append(facts);host.append(section);}
function renderSchema(host,item,includeTraversal){schema(item).diagnostics.top_level_chunk_ids.forEach(topId=>{const top=schema(item).chunks.find(row=>row.id===topId);addChunk(host,item,top);leavesFor(item,top).filter(row=>row.id!==top.id).forEach(leaf=>addChunk(host,item,leaf));});const edges=schema(item).schema_edges.filter(edge=>edge.edge_kind!=="SUPPORTED_CHUNK_MEMBERSHIP"&&(includeTraversal||edge.required_for_reconstruction));const section=el("section","relation-list");section.append(el("h3",null,includeTraversal?"Reading path and supported implications":"Necessary implications"));edges.forEach(edge=>{const row=el("div","relation-row");row.dataset.edgeId=edge.id;row.append(el("strong",null,edge.relation.replaceAll("_"," ")));row.append(el("span",null,`${edge.from} → ${edge.to}${edge.required_for_reconstruction?" · required for reconstruction":""}`));section.append(row);});host.append(section);}
function renderAudit(host,item){const cards=[
  ["TOP-LEVEL UNITS",`${item.metrics.independent_top_level_units_before} before · ${item.metrics.independent_top_level_units_after} after · ratio ${item.metrics.top_level_unit_ratio}`],
  ["SEMANTICS",`${item.semantic_preservation_audit.item_count} preserved · ${item.semantic_preservation_audit.forbidden_status_count} forbidden outcomes`],
  ["EXPLANATION",`${item.explanatory_preservation_audit.block_count} blocks · ${item.explanatory_preservation_audit.traversal_count} transitions · ${item.explanatory_preservation_audit.traversal_loss_count} losses`],
  ["IMPLICATIONS",`${item.implication_preservation_audit.preserved_count}/${item.implication_preservation_audit.material_implication_count} preserved`],
  ["SCHEMA SUPPORT",`${item.chunk_membership_support_audit.supported_count} memberships · ${item.schema_edge_support_audit.supported_count} edges supported`],
  ["PROVENANCE",`${item.provenance_recoverability_audit.semantic_items_with_exact_evidence}/${item.provenance_recoverability_audit.semantic_item_count} items recoverable`]
];const grid=el("div","audit-grid");cards.forEach(([label,text])=>{const card=el("article","audit-card");card.append(el("strong",null,label));card.append(el("p",null,text));grid.append(card);});host.append(grid);}
function renderMetrics(item){const host=byId("metric-strip");host.replaceChildren();[["BLOCKS",item.metrics.explanatory_block_count,"frozen"],["TOP LEVEL",item.metrics.top_level_conceptual_chunk_count,`ratio ${item.metrics.top_level_unit_ratio}`],["FACTS",item.metrics.frozen_semantic_item_count,"all explicit"],["IMPLICATIONS",item.metrics.material_implications_preserved,"all preserved"]].forEach(([label,value,note])=>{const card=el("div","metric");card.append(el("strong",null,String(value)));card.append(document.createTextNode(`${label} · ${note}`));host.append(card);});}
function renderResolution(){const item=current(),host=byId("resolution-host");host.replaceChildren();host.dataset.caseIdentity=item.case_identity;host.dataset.mode=state.mode;["S0","S1","S2","AUDIT"].forEach(mode=>byId(`mode-${mode.toLowerCase()}`).setAttribute("aria-pressed",String(state.mode===mode)));if(state.mode==="S0"){byId("resolution-label").textContent="S0 · EXACT SPEC-061 EXPLANATORY BASELINE";renderS0(host,item);}else if(state.mode==="S1"){byId("resolution-label").textContent="S1 · CHUNKED TEXTUAL SCHEMA";renderSchema(host,item,false);}else if(state.mode==="S2"){byId("resolution-label").textContent="S2 · SCHEMA WITH EXPLANATORY TRAVERSAL";renderSchema(host,item,true);}else{byId("resolution-label").textContent="PRESERVATION AND SUPPORT AUDIT";renderAudit(host,item);}renderMetrics(item);state.selectedChunk=null;defaultTrace();}
function renderCase(){const item=current();byId("case-counter").textContent=`CASE ${item.review_index} OF ${state.packet.cases.length}`;byId("case-title").textContent=item.source_identity.title;byId("case-domain").textContent=`${item.source_identity.domain} · ${item.source_identity.institutional_publisher}`;[...byId("case-list").querySelectorAll("button")].forEach((button,index)=>button.setAttribute("aria-current",String(index===state.index)));renderResolution();}
function selectCase(index){state.index=(index+state.packet.cases.length)%state.packet.cases.length;state.mode="S0";renderCase();}
function setMode(mode){if(!["S0","S1","S2","AUDIT"].includes(mode))throw new Error(`Unknown mode ${mode}`);state.mode=mode;renderResolution();}
function installCases(){const host=byId("case-list");state.packet.cases.forEach((item,index)=>{const row=el("li"),button=el("button",null,item.source_identity.title);button.type="button";button.dataset.caseIdentity=item.case_identity;button.addEventListener("click",()=>selectCase(index));row.append(button);host.append(row);});}
function snapshot(){const item=current(),host=byId("resolution-host");return{case_identity:item.case_identity,host_case_identity:host.dataset.caseIdentity,mode:state.mode,text:host.querySelector(".baseline-prose")?.dataset.viewText||null,chunk_ids:[...host.querySelectorAll("[data-chunk-id]")].map(node=>node.dataset.chunkId),semantic_ids:[...host.querySelectorAll("[data-semantic-id]")].map(node=>node.dataset.semanticId),edge_ids:[...host.querySelectorAll("[data-edge-id]")].map(node=>node.dataset.edgeId),audit_cards:host.querySelectorAll(".audit-card").length,selected_chunk:state.selectedChunk};}
function sameIdentities(left,right){return left.length===right.length&&JSON.stringify([...left].sort())===JSON.stringify([...right].sort());}
function machineGate(){const start={index:state.index,mode:state.mode},rows=[];for(let index=0;index<state.packet.cases.length;index++){selectCase(index);const item=current(),expectedChunks=schema(item).chunks.map(row=>row.id),expectedSemantic=item.semantic_items.map(row=>row.upstream_id),expectedEdges=schema(item).schema_edges.filter(row=>row.edge_kind!=="SUPPORTED_CHUNK_MEMBERSHIP").map(row=>row.id);setMode("S0");const s0=snapshot();setMode("S1");const s1=snapshot(),first=byId("resolution-host").querySelector("[data-chunk-id]");if(first)first.click();const selected=snapshot();setMode("S2");const s2=snapshot();setMode("AUDIT");const audit=snapshot(),resolutionHost=byId("resolution-host");rows.push({case_identity:item.case_identity,identity_exact:s0.case_identity===s0.host_case_identity,s0_text_exact:s0.text===item.views.S0.text,s1_chunks_exact:JSON.stringify(s1.chunk_ids)===JSON.stringify(expectedChunks),s2_chunks_exact:JSON.stringify(s2.chunk_ids)===JSON.stringify(expectedChunks),s1_semantics_exact:sameIdentities(s1.semantic_ids,expectedSemantic),s2_semantics_exact:sameIdentities(s2.semantic_ids,expectedSemantic),s2_edges_exact:JSON.stringify(s2.edge_ids)===JSON.stringify(expectedEdges),peer_lineage:item.views.S1.depends_on.length===0&&item.views.S2.depends_on.length===0,trace_selection_works:selected.selected_chunk===expectedChunks[0],audit_visible:audit.audit_cards===6,no_visualization_dom:resolutionHost.querySelectorAll("svg,canvas,.diagram,.chart").length===0});}selectCase(start.index);setMode(start.mode);return{case_count:state.packet.cases.length,all_cases_pass:rows.every(row=>Object.entries(row).filter(([key])=>key!=="case_identity").every(([,value])=>value===true)),rows,errors:[...state.errors],warnings:[...state.warnings]};}

async function install(){try{const[packet,rubric]=await Promise.all([fetch("cases.json").then(response=>response.json()),fetch("owner-review-rubric.json").then(response=>response.json())]);state.packet=packet;installCases();rubric.criteria.forEach(item=>byId("rubric-list").append(el("li",null,`${item.label} — ${item.question}`)));byId("previous-case").addEventListener("click",()=>selectCase(state.index-1));byId("next-case").addEventListener("click",()=>selectCase(state.index+1));["S0","S1","S2","AUDIT"].forEach(mode=>byId(`mode-${mode.toLowerCase()}`).addEventListener("click",()=>setMode(mode)));renderCase();window.__SPEC062_REVIEW__={snapshot,selectCase,setMode,machineGate,state};const contract=byId("spec062-contract"),gate=machineGate();contract.dataset.browserGate=JSON.stringify(gate);contract.dataset.browserReady="true";document.dispatchEvent(new CustomEvent("spec062-review-ready"));}catch(error){state.errors.push(String(error));document.body.dataset.loadError=String(error);throw error;}}
window.addEventListener("error",event=>state.errors.push(event.message));
window.addEventListener("unhandledrejection",event=>state.errors.push(String(event.reason)));
install();
