"use strict";

// The path owns traversal history only. Canonical semantic focus remains owned
// by SPEC-029, and the explanatory projection remains owned by SPEC-030/031.
const pathState={packet:null,nodes:[],currentNodeId:null,pendingVisitedNodeId:null,syncScheduled:false};
const pathAtomic=window.__SPEC029_ATOMIC__;
function pathDepthApi(){return window.__SPEC024_DEPTH__;}

function pathObject(key){const item=pathState.packet.catalog.find(value=>value.object_key===key);if(!item)throw new Error(`SPEC-032 unknown trusted object ${key}`);return item;}
function pathCurrentNode(){return pathState.nodes.find(item=>item.pathNodeId===pathState.currentNodeId)||null;}
function pathObjectKey(kind,identity,domainId){return kind==="orientation"?`orientation:domain:${domainId}`:`${kind}:${identity}`;}
function pathProbe(item){const node=document.createElement("span");node.dataset.atomicId=item.semantic_identity||item.orientation_identity;node.dataset.atomicKind=item.kind==="orientation"?"concept":item.kind;node.dataset.atomicAncestry=item.ancestry.join("/");node.dataset.atomicSurface="path";node.dataset.atomicDomain=item.domain_id;node.dataset.atomicRepresentationIndex=String(item.representation_index);return pathAtomic.resolve(node);}
function pathEnsureSemanticContext(item){const depth=pathDepthApi(),expanded=depth.isExpanded();if(item.ancestry.length){const current=pathAtomic.snapshot();if(current.activeContext.domainId!==item.domain_id||current.activeContext.representationIndex!==item.representation_index)pathAtomic.replaceContext(pathProbe(item).context);if(!expanded)depth.expand();}else if(expanded)depth.collapse();}
function pathCommitSemantic(item){pathEnsureSemanticContext(item);const occurrence=pathProbe(item);if(item.kind==="orientation")pathAtomic.replaceContext(occurrence.context);else pathAtomic.dispatch("select",occurrence);}
function pathAppend(item,parentId){const existing=pathState.nodes.find(node=>node.parentPathNodeId===parentId&&node.objectKey===item.object_key);if(existing)return existing.pathNodeId;const nodeId=`path-${String(pathState.nodes.length+1).padStart(4,"0")}`;pathState.nodes.push({pathNodeId:nodeId,objectKey:item.object_key,semanticIdentity:item.semantic_identity,kind:item.kind,label:item.label,domainId:item.domain_id,parentPathNodeId:parentId,createdIndex:pathState.nodes.length});return nodeId;}
function pathTravelObject(key){const item=pathObject(key);pathState.pendingVisitedNodeId=null;pathCommitSemantic(item);pathScheduleSync();}
function pathActivateVisited(nodeId){const node=pathState.nodes.find(item=>item.pathNodeId===nodeId);if(!node)throw new Error(`SPEC-032 unknown visited path node ${nodeId}`);pathState.pendingVisitedNodeId=nodeId;pathCommitSemantic(pathObject(node.objectKey));pathScheduleSync();}
function pathSemanticObject(){const state=pathAtomic.snapshot();if(!state.activeContext)return null;if(state.selected){const ancestry=state.selectedAncestry||[],matches=pathState.packet.catalog.filter(item=>item.kind===state.selected.kind&&item.semantic_identity===state.selected.identity),exact=matches.find(item=>JSON.stringify(item.ancestry)===JSON.stringify(ancestry));return exact||matches[0]||null;}return pathState.packet.catalog.find(item=>item.object_key===pathObjectKey("orientation",null,state.activeContext.domainId))||null;}
function pathSyncFromSemantic(){const item=pathSemanticObject();if(!item)return;const pending=pathState.pendingVisitedNodeId;if(pending){const visited=pathState.nodes.find(node=>node.pathNodeId===pending);if(!visited||visited.objectKey!==item.object_key)throw new Error("SPEC-032 visited-node semantic restoration mismatch");pathState.currentNodeId=pending;pathState.pendingVisitedNodeId=null;}else{const current=pathCurrentNode();if(!current)pathState.currentNodeId=pathAppend(item,null);else if(current.objectKey!==item.object_key)pathState.currentNodeId=pathAppend(item,current.pathNodeId);}pathRender();}
function pathScheduleSync(){if(pathState.syncScheduled)return;pathState.syncScheduled=true;requestAnimationFrame(()=>{pathState.syncScheduled=false;pathSyncFromSemantic();});}

function pathVisitedKeys(){return new Set(pathState.nodes.map(item=>item.objectKey));}
function pathSuggestions(item){const byKey=new Map(pathState.packet.catalog.map(value=>[value.object_key,value])),visited=pathVisitedKeys(),candidates=new Map();function add(key,priority,basis,basisIdentity){const target=byKey.get(key);if(!target||key===item.object_key)return;const value={targetObjectKey:key,targetLabel:target.label,targetKind:target.kind,priority,basis,basisIdentity},old=candidates.get(key);if(!old||priority<old.priority||(priority===old.priority&&basisIdentity<old.basisIdentity))candidates.set(key,value);}if(item.kind==="orientation")pathState.packet.catalog.filter(value=>value.kind==="concept"&&value.domain_id===item.domain_id).forEach(value=>add(value.object_key,30,"DOMAIN_ENTRY",item.orientation_identity));else if(item.kind==="concept")pathState.packet.continuations.forEach(link=>{const endpoints=[link.source_object_key,link.target_object_key];if(!endpoints.includes(item.object_key))return;const other=endpoints[0]===item.object_key?endpoints[1]:endpoints[0];if(link.basis==="CANONICAL_RELATIONSHIP"){add(other,10,link.basis,link.basis_identity);add(link.relationship_object_key,30,"CANONICAL_RELATIONSHIP_OBJECT",link.basis_identity);}else add(other,20,link.basis,link.basis_identity);});else if(item.kind==="canonical")pathState.packet.continuations.filter(link=>link.relationship_object_key===item.object_key).forEach(link=>{add(link.source_object_key,10,"CANONICAL_ENDPOINT",link.basis_identity);add(link.target_object_key,10,"CANONICAL_ENDPOINT",link.basis_identity);});else if(item.kind==="explanation")pathState.packet.continuations.filter(link=>link.basis==="SHARED_SOURCE_EXPLANATION"&&link.basis_identity===item.semantic_identity).forEach(link=>{add(link.source_object_key,10,"SOURCE_EXPLANATION_PARTICIPANT",link.basis_identity);add(link.target_object_key,10,"SOURCE_EXPLANATION_PARTICIPANT",link.basis_identity);});return [...candidates.values()].sort((left,right)=>Number(visited.has(left.targetObjectKey))-Number(visited.has(right.targetObjectKey))||left.priority-right.priority||left.targetLabel.localeCompare(right.targetLabel)||left.targetObjectKey.localeCompare(right.targetObjectKey)||left.basisIdentity.localeCompare(right.basisIdentity));}
function pathSuggestionLabel(value){if(value.targetKind==="canonical"){const target=pathObject(value.targetObjectKey),scope=target.ancestry.length?" · deeper source assertion":"";return`Understand ${value.targetLabel}${scope}`;}if(value.basis==="SHARED_SOURCE_EXPLANATION")return`Follow the source explanation to ${value.targetLabel}`;return`Explore ${value.targetLabel}`;}
function pathBasisLabel(value){if(value.basis==="CANONICAL_RELATIONSHIP"||value.basis==="CANONICAL_ENDPOINT"||value.basis==="CANONICAL_RELATIONSHIP_OBJECT")return"Grounded canonical connection";if(value.basis==="SHARED_SOURCE_EXPLANATION"||value.basis==="SOURCE_EXPLANATION_PARTICIPANT")return"Grounded in shared source evidence";return"Trusted concept in this domain";}

function pathTreeNode(node,children){const item=document.createElement("li"),button=document.createElement("button");button.type="button";button.className=`path-node-button${node.pathNodeId===pathState.currentNodeId?" is-current":""}`;button.dataset.pathNodeId=node.pathNodeId;button.setAttribute("aria-current",node.pathNodeId===pathState.currentNodeId?"location":"false");const kind=document.createElement("span"),label=document.createElement("span");kind.className="path-kind";kind.textContent=node.kind==="canonical"?"relation":node.kind;label.className="path-label";label.textContent=node.label;button.append(kind,label);button.addEventListener("click",()=>pathActivateVisited(node.pathNodeId));item.append(button);const descendants=children.get(node.pathNodeId)||[];if(descendants.length){const list=document.createElement("ul");descendants.forEach(child=>list.append(pathTreeNode(child,children)));item.append(list);}return item;}
function pathRenderTree(root){const children=new Map();pathState.nodes.forEach(node=>{if(!children.has(node.parentPathNodeId))children.set(node.parentPathNodeId,[]);children.get(node.parentPathNodeId).push(node);});children.forEach(items=>items.sort((left,right)=>left.createdIndex-right.createdIndex));const list=document.createElement("ul");list.className="path-tree";(children.get(null)||[]).forEach(node=>list.append(pathTreeNode(node,children)));root.append(list);}
function pathRenderSuggestions(){const root=document.getElementById("exploration-suggestions"),current=pathCurrentNode();root.replaceChildren();const heading=document.createElement("h3"),intro=document.createElement("p"),list=document.createElement("div");heading.textContent="Explore next";intro.textContent="Trusted continuations from the current learning object";list.className="path-suggestion-list";root.append(heading,intro,list);if(!current)return;pathSuggestions(pathObject(current.objectKey)).slice(0,6).forEach(value=>{const button=document.createElement("button"),basis=document.createElement("small");button.type="button";button.className="path-suggestion";button.dataset.suggestionObjectKey=value.targetObjectKey;button.append(document.createTextNode(pathSuggestionLabel(value)));basis.textContent=pathBasisLabel(value);button.append(basis);button.addEventListener("click",()=>pathTravelObject(value.targetObjectKey));list.append(button);});if(!list.childElementCount)list.textContent="No further trusted continuation is available in this fixed packet.";}
function pathAudit(){const semantic=pathSemanticObject(),current=pathCurrentNode(),learning=document.getElementById("spec030-learning-contract")?.dataset.identity||"NONE",semanticIdentity=semantic?.semantic_identity||"NONE",marker=document.getElementById("spec032-learning-path-contract");marker.dataset.currentPathObjectKey=current?.objectKey||"NONE";marker.dataset.currentPathSemanticIdentity=current?.semanticIdentity||"NONE";marker.dataset.currentLearningObjectKey=semantic?.object_key||"NONE";marker.dataset.learningSurfaceIdentity=learning;marker.dataset.currentObjectAgreement=current?.objectKey===semantic?.object_key?"PASS":"FAIL";marker.dataset.learningIdentityAgreement=semanticIdentity===learning?"PASS":"PENDING_PROJECTION";marker.dataset.pathNodeCount=String(pathState.nodes.length);marker.dataset.traversalEdgeCount=String(Math.max(0,pathState.nodes.length-1));marker.dataset.canonicalPredicateOnTraversalEdgeCount="0";}
function pathRender(){const root=document.getElementById("learning-path");root.replaceChildren();const domains=document.createElement("nav");domains.className="path-domain-switcher";domains.setAttribute("aria-label","Start or continue in another trusted domain");pathState.packet.catalog.filter(item=>item.kind==="orientation").forEach(item=>{const button=document.createElement("button");button.type="button";button.textContent=item.label;button.addEventListener("click",()=>pathTravelObject(item.object_key));domains.append(button);});const intro=document.createElement("p");intro.className="path-intro";intro.textContent="This map records where you travelled. Its lines mean ‘travelled to’, not a domain predicate.";root.append(domains,intro);pathRenderTree(root);pathRenderSuggestions();pathAudit();}

function pathInstall(packet){pathState.packet=packet;document.body.classList.add("spec032-learning-path");document.querySelector("#navigation-pane .role-label").textContent="MY JOURNEY";document.querySelector("#navigation-pane h2").textContent="Learning path";document.getElementById("navigation-pane").setAttribute("aria-label","Learner traversal history");document.querySelector(".fixture-label").textContent="Traversal history + trusted deterministic learning representations";const root=document.createElement("div");root.id="learning-path";root.setAttribute("aria-label","Visited learning path");document.getElementById("nav-viewport").append(root);const suggestions=document.createElement("section");suggestions.id="exploration-suggestions";suggestions.setAttribute("aria-label","Explore next");document.getElementById("learning-pane").append(suggestions);const marker=document.createElement("div");marker.id="spec032-learning-path-contract";marker.hidden=true;marker.dataset.pathStateOwner="pathState";marker.dataset.semanticStateOwner="SPEC-029 atomicLearnerState";marker.dataset.pathEdgeSemantics="TRAVELLED";marker.dataset.canonicalPredicateOnTraversalEdgeCount="0";marker.dataset.sourceEvidenceCreatesTraversalStep="false";marker.dataset.suggestionResolver="trusted deterministic catalog + canonical adjacency + shared source participants";marker.dataset.depthIsPathRuleInput="false";document.body.append(marker);new MutationObserver(pathScheduleSync).observe(document.getElementById("spec029-atomic-contract"),{attributes:true});new MutationObserver(pathScheduleSync).observe(document.getElementById("spec030-learning-contract"),{attributes:true});const initial=pathObject("orientation:domain:electromagnetism");pathState.currentNodeId=pathAppend(initial,null);pathCommitSemantic(initial);pathScheduleSync();document.dispatchEvent(new CustomEvent("spec032-learning-path-ready"));}

function pathInstallWhenReady(packet){if(!pathAtomic||!window.__SPEC024_DEPTH__||!window.__SPEC030_LEARNING__||!window.__SPEC031_MULTIPLICITY__||!document.getElementById("spec030-learning-contract")||!document.getElementById("spec031-multiplicity-contract")){requestAnimationFrame(()=>pathInstallWhenReady(packet));return;}pathInstall(packet);}
fetch("learning-path-fixture.json").then(response=>response.json()).then(pathInstallWhenReady).catch(error=>console.error("SPEC-032 learning-path seam failed",error));
window.__SPEC032_PATH__={snapshot:()=>({currentNodeId:pathState.currentNodeId,nodes:pathState.nodes.map(item=>({...item})),edges:pathState.nodes.filter(item=>item.parentPathNodeId).map(item=>({sourcePathNodeId:item.parentPathNodeId,targetPathNodeId:item.pathNodeId,semantics:"TRAVELLED",canonicalPredicate:null}))}),suggestions:()=>pathCurrentNode()?pathSuggestions(pathObject(pathCurrentNode().objectKey)):[],travel:pathTravelObject,activate:pathActivateVisited,contract:()=>{const marker=document.getElementById("spec032-learning-path-contract");return marker?{...marker.dataset}:null;}};
