"use strict";

const learnerState={fixture:null,depthSnapshot:null,currentRegion:null};
const learnerById=id=>document.getElementById(id);
const learnerElement=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
const learnerSalience={PRIMARY:0,SECONDARY:1,SPARSE:2,HIGH:3};
function learnerDomain(id){return learnerState.fixture.domains.find(item=>item.domain_id===id);}
function learnerOrientationIndex(domain){return domain.learning_model.representations.map((item,index)=>({item,index})).sort((a,b)=>(learnerSalience[a.item.salience]??99)-(learnerSalience[b.item.salience]??99)||b.item.nodes.length-a.item.nodes.length||a.item.id.localeCompare(b.item.id))[0].index;}
function learnerConceptIndex(domain,entityId){const candidates=domain.learning_model.representations.map((item,index)=>({item,index})).filter(value=>value.item.nodes.some(node=>node.entity_id===entityId));if(!candidates.length)throw new Error(`No existing representation contains ${entityId}`);return candidates.sort((a,b)=>(learnerSalience[a.item.salience]??99)-(learnerSalience[b.item.salience]??99)||a.item.id.localeCompare(b.item.id))[0].index;}
function learnerRelationshipIndex(domain,relationshipId){const candidates=domain.learning_model.representations.map((item,index)=>({item,index})).filter(value=>value.item.edges.some(edge=>edge.relationship_ids.includes(relationshipId)));if(!candidates.length)throw new Error(`No existing representation contains ${relationshipId}`);return candidates.sort((a,b)=>(learnerSalience[a.item.salience]??99)-(learnerSalience[b.item.salience]??99)||a.item.id.localeCompare(b.item.id))[0].index;}
function learnerSetRegion(domainId){learnerState.currentRegion=domainId;document.querySelectorAll(".domain-region,.domain-region-label").forEach(node=>node.classList.remove("current-region"));const index=learnerState.fixture.domains.findIndex(item=>item.domain_id===domainId);document.querySelectorAll(".domain-region")[index]?.classList.add("current-region");document.querySelectorAll(".domain-region-label")[index]?.classList.add("current-region");}
function learnerContext(domainLabel,focus){const desired=[domainLabel,focus],current=[...learnerById("context-path").querySelectorAll("span")].map(node=>node.textContent);if(current.length===desired.length&&current.every((value,index)=>value===desired[index]))return;learnerById("context-path").replaceChildren(...desired.map(text=>learnerElement("span",text)));}
function learnerRefreshChrome(){if(window.__SPEC021_PROJECTION__?.isActive())return;const api=window.__BASELINE003_SEAM__,state=api.state,domain=learnerDomain(state.domainId),focus=state.selectedEntityId?learnerState.fixture.navigation.nodes.find(node=>node.entity_id===state.selectedEntityId)?.label:state.selectedRelationshipId?"Relationship":"Orientation";learnerSetRegion(state.domainId);learnerContext(domain.label,focus);if(!state.selectedEntityId&&!state.selectedRelationshipId)learnerById("nav-summary").textContent=`${domain.label} · Orientation`;learnerLocalDepth();}
function learnerFitRegion(domain){const api=window.__BASELINE003_SEAM__,state=api.state,region=domain.world_region,viewport=learnerState.fixture.navigation.camera.viewport,padding=100,scale=Math.min(viewport.width/(region.width+padding),viewport.height/(region.height+padding),learnerState.fixture.navigation.camera.zoom.max_scale),target=api.clampCamera({x:region.x+region.width/2-viewport.width/(2*scale),y:region.y+region.height/2-viewport.height/(2*scale),scale}),snapshot=api.cameraSnapshot();if(!api.sameCamera(snapshot.camera,target)){state.backStack.push(snapshot);state.forwardStack=[];api.setCamera(target,true);}}
function learnerEnterRegion(domainId){const api=window.__BASELINE003_SEAM__,state=api.state,domain=learnerDomain(domainId);if(window.__SPEC021_PROJECTION__?.isActive())learnerReturnDepth();state.domainId=domainId;state.representationIndex=learnerOrientationIndex(domain);state.selectedEntityId=null;state.selectedRelationshipId=null;state.previewEntityId=null;state.previewRelationshipId=null;api.renderLearning();api.updateWorkspace();learnerFitRegion(domain);learnerSetRegion(domainId);learnerContext(domain.label,"Orientation");learnerById("nav-summary").textContent=`${domain.label} · Orientation`;}
function learnerSelectConcept(entityId){const api=window.__BASELINE003_SEAM__,node=learnerState.fixture.navigation.nodes.find(item=>item.entity_id===entityId),domain=learnerDomain(node.domain_id);if(window.__SPEC021_PROJECTION__?.isActive())learnerReturnDepth();const index=learnerConceptIndex(domain,entityId),changed=api.state.domainId!==node.domain_id||api.state.representationIndex!==index;api.state.domainId=node.domain_id;api.state.representationIndex=index;if(changed)api.renderLearning();api.setEntityFocus(entityId);learnerRefreshChrome();}
function learnerSelectRelationship(relationshipId){const api=window.__BASELINE003_SEAM__,edge=learnerState.fixture.navigation.edges.find(item=>item.relationship_ids.includes(relationshipId)),domain=learnerDomain(edge.domain_id);if(window.__SPEC021_PROJECTION__?.isActive())learnerReturnDepth();const index=learnerRelationshipIndex(domain,relationshipId),changed=api.state.domainId!==edge.domain_id||api.state.representationIndex!==index;api.state.domainId=edge.domain_id;api.state.representationIndex=index;if(changed)api.renderLearning();api.setRelationshipFocus(relationshipId);learnerRefreshChrome();}
function learnerEnterDepth(){const api=window.__BASELINE003_SEAM__;if(api.state.selectedEntityId!=="double-slit-experiment")throw new Error("Depth is not admitted for this concept");learnerState.depthSnapshot=api.cameraSnapshot();window.__SPEC021_PROJECTION__.enter();learnerById("context-path").replaceChildren(...["Electromagnetism","double-slit experiment","Deeper"].map(text=>learnerElement("span",text)));const returnButton=learnerElement("button","Return","projection-return");returnButton.addEventListener("click",learnerReturnDepth);document.querySelector(".projection-meta").append(returnButton);learnerById("clear-selection").disabled=true;}
function learnerReturnDepth(){if(!window.__SPEC021_PROJECTION__?.isActive())return;window.__SPEC021_PROJECTION__.exit();learnerState.depthSnapshot=null;learnerRefreshChrome();}
function learnerLocalDepth(){const existing=learnerById("learning-detail").querySelector(".contextual-depth"),eligible=!window.__SPEC021_PROJECTION__?.isActive()&&window.__BASELINE003_SEAM__.state.selectedEntityId==="double-slit-experiment";if(!eligible){existing?.remove();return;}if(existing)return;const button=learnerElement("button","Explore deeper","contextual-depth");button.addEventListener("click",learnerEnterDepth);learnerById("learning-detail").append(button);}
function learnerBindRegions(){document.querySelectorAll(".domain-region").forEach((node,index)=>{const domain=learnerState.fixture.domains[index];node.classList.add("region-entry");node.setAttribute("tabindex","0");node.setAttribute("role","button");node.setAttribute("aria-label",`Enter ${domain.label}`);node.addEventListener("click",event=>{event.stopPropagation();learnerEnterRegion(domain.domain_id);});node.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();learnerEnterRegion(domain.domain_id);}});});document.querySelectorAll(".domain-region-label").forEach((node,index)=>{const domain=learnerState.fixture.domains[index];node.parentNode.append(node);node.classList.add("region-entry");node.setAttribute("tabindex","0");node.setAttribute("role","button");node.setAttribute("aria-label",`Enter ${domain.label}`);node.addEventListener("click",event=>{event.stopPropagation();learnerEnterRegion(domain.domain_id);});node.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();learnerEnterRegion(domain.domain_id);}});});}
function learnerHandleSelection(event,kind){const node=event.target.closest(kind==="navigation"?".nav-node":".learn-node"),edge=event.target.closest(kind==="navigation"?".nav-edge-hit":".learn-edge-hit");if(!node&&!edge)return false;event.preventDefault();event.stopImmediatePropagation();if(node){learnerSelectConcept(node.dataset.entityId);return true;}const item=kind==="navigation"?learnerState.fixture.navigation.edges.find(value=>value.edge_key===edge.dataset.edgeKey):learnerDomain(window.__BASELINE003_SEAM__.state.domainId).learning_model.representations[window.__BASELINE003_SEAM__.state.representationIndex].edges.find(value=>value.edge_key===edge.dataset.edgeKey);learnerSelectRelationship(item.relationship_ids[0]);return true;}
function learnerInterceptSelection(){[["nav-graph","navigation"],["learning-graph","learning"]].forEach(([id,kind])=>{const graph=learnerById(id);graph.addEventListener("click",event=>learnerHandleSelection(event,kind),{capture:true});graph.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" ")learnerHandleSelection(event,kind);},{capture:true});});learnerById("clear-selection").addEventListener("click",event=>{if(window.__SPEC021_PROJECTION__?.isActive()){event.stopImmediatePropagation();window.__SPEC021_PROJECTION__.clear();event.currentTarget.disabled=true;}else requestAnimationFrame(learnerRefreshChrome);},{capture:true});}
function learnerInstall(){const api=window.__BASELINE003_SEAM__;if(!api?.state.fixture||!window.__SPEC021_PROJECTION__){requestAnimationFrame(learnerInstall);return;}learnerState.fixture=api.state.fixture;if(new URLSearchParams(location.search).get("debug")==="1")document.body.classList.add("evaluator-mode");learnerBindRegions();learnerInterceptSelection();const observer=new MutationObserver(()=>requestAnimationFrame(learnerRefreshChrome));observer.observe(learnerById("context-path"),{childList:true});observer.observe(learnerById("learning-detail"),{childList:true});learnerRefreshChrome();}
learnerInstall();
