"use strict";
const S={fixture:null,camera:null,level:"PARENT",selected:null,pan:null,back:[],forward:[]};
const NS="http://www.w3.org/2000/svg",$=id=>document.getElementById(id);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function se(tag,a={}){const n=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));return n}
function activate(event,fn){if(event.key==="Enter"||event.key===" "){event.preventDefault();fn()}}
function markers(svg){const defs=se("defs");[["projection-arrow","#263a31"],["projection-arrow-selected","#176b50"],["nav-arrow","#697870"]].forEach(([id,fill])=>{const m=se("marker",{id,viewBox:"0 0 10 10",refX:9,refY:5,markerWidth:7,markerHeight:7,orient:"auto"});m.append(se("path",{d:"M0 0L10 5L0 10z",fill}));defs.append(m)});svg.append(defs)}
function navNode(id){return S.fixture.navigation.nodes.find(n=>n.entity_id===id)}
function pModel(){return S.fixture.domains[0].learning_model}
function pRep(){return pModel().representations[0]}
function proj(){return S.fixture.semantic_depth.projection}
function routePath(r){const p=r.points;if(r.path_kind==="LINE")return`M${p[0].x} ${p[0].y}L${p[1].x} ${p[1].y}`;if(r.path_kind==="QUADRATIC")return`M${p[0].x} ${p[0].y}Q${p[1].x} ${p[1].y} ${p[2].x} ${p[2].y}`;return`M${p[0].x} ${p[0].y}C${p[1].x} ${p[1].y} ${p[2].x} ${p[2].y} ${p[3].x} ${p[3].y}`}
function viewSize(){const v=S.fixture.navigation.camera.viewport;return{width:v.width/S.camera.scale,height:v.height/S.camera.scale}}
function clamp(c){const z=S.fixture.navigation.camera.zoom,b=S.fixture.navigation.world.bounds,scale=Math.min(z.max_scale,Math.max(z.min_scale,c.scale)),v=S.fixture.navigation.camera.viewport,size={width:v.width/scale,height:v.height/scale};return{x:Math.max(b.min_x,Math.min(b.max_x-size.width,c.x)),y:Math.max(b.min_y,Math.min(b.max_y-size.height,c.y)),scale}}
function same(a,b){return Math.abs(a.x-b.x)<.001&&Math.abs(a.y-b.y)<.001&&Math.abs(a.scale-b.scale)<.000001}
function viewbox(){const v=viewSize();$("nav-graph").setAttribute("viewBox",`${S.camera.x} ${S.camera.y} ${v.width} ${v.height}`);$("scale-status").textContent=`${Math.round(S.camera.scale*100)}%`;buttons()}
function setCamera(c,remember=true){c=clamp(c);if(remember&&!same(c,S.camera)){S.back.push({...S.camera});S.forward=[]}S.camera=c;viewbox()}
function centerOn(id){const p=navNode(id).world,v=viewSize(),visible=p.x>S.camera.x+84&&p.x<S.camera.x+v.width-84&&p.y>S.camera.y+30&&p.y<S.camera.y+v.height-30;if(!visible)setCamera({x:p.x-v.width/2,y:p.y-v.height/2,scale:S.camera.scale})}
function select(kind,id){S.selected={kind,id};if(kind==="concept")centerOn(id);attention();detail();buttons()}
function clear(){S.selected=null;attention();detail();buttons()}
function buttons(){$("clear-selection").disabled=!S.selected;$("history-back").disabled=!S.back.length;$("history-forward").disabled=!S.forward.length}
function toggle(){S.level=S.level==="PARENT"?"PROJECTION":"PARENT";S.selected=S.level==="PROJECTION"?null:{kind:"concept",id:S.fixture.semantic_depth.focus_entity_id};renderLearning();attention();detail();buttons()}
function context(){const deeper=S.level==="PROJECTION";$("context-path").replaceChildren(...["Quantum mechanics","double-slit experiment",deeper?"Explanatory projection":"Parent context"].map(x=>el("span",x)));$("depth-toggle").textContent=deeper?"Parent context":"Explore deeper";$("depth-toggle").setAttribute("aria-pressed",String(deeper));$("learning-pane").classList.toggle("is-projection",deeper)}
function resetDetail(){$("learning-detail").replaceChildren(el("span","Explanation & evidence","eyebrow"),el("h3","Select a concept or relationship"),el("p","Strong arrows are canonical. Dashed attachments are source-backed explanations."))}
function addEvidence(detail,spans,hidden){const button=el("button",hidden?"Show exact source evidence":"Exact source evidence","evidence-button"),box=el("div",undefined,"evidence-block");if(hidden)box.hidden=true;spans.forEach(s=>{box.append(el("blockquote",`“${s.quote}”`),el("small",`${s.document_id} · characters ${s.start_char}–${s.end_char}`))});if(hidden)button.addEventListener("click",()=>{box.hidden=!box.hidden;button.textContent=box.hidden?"Show exact source evidence":"Hide exact source evidence"});else button.disabled=true;detail.append(button,box)}
function detail(){if(!S.selected){resetDetail();return}const d=$("learning-detail"),p=proj();if(S.level==="PARENT"){const r=pRep(),node=r.nodes.find(n=>n.entity_id===S.selected.id),edge=r.edges.find(e=>e.relationship_ids.includes(S.selected.id));if(node){d.replaceChildren(el("span","Selected · parent concept","eyebrow"),el("h3",node.label),el("p",node.description))}else if(edge){d.replaceChildren(el("span","Trusted canonical relationship","eyebrow"),el("h3",edge.relationship_label),el("p",edge.meaning));addEvidence(d,edge.evidence,false)}else resetDetail();return}
  if(S.selected.kind==="concept"){const n=p.concepts.find(x=>x.entity_id===S.selected.id);d.replaceChildren(el("span",n.is_focus?"Current focus · concept":"Selected · concept","eyebrow"),el("h3",n.label),el("p",n.description));return}
  if(S.selected.kind==="canonical"){const x=p.canonical_items.find(x=>x.id===S.selected.id);d.replaceChildren(el("span","Trusted canonical relationship","eyebrow"),el("h3",x.relationship_type.replaceAll("_"," ")),el("p",x.predicate_meaning),el("p",x.statement));const dl=el("dl",undefined,"detail-grid");[["Source",x.source_entity_id],["Target",x.target_entity_id],["Semantic tier",x.semantic_tier]].forEach(([a,b])=>dl.append(el("dt",a),el("dd",b)));d.append(dl);addEvidence(d,x.evidence,false);return}
  const x=p.explanatory_items.find(x=>x.id===S.selected.id);d.replaceChildren(el("span","Source-backed explanation · non-canonical","eyebrow"),el("h3",x.short_label),el("div","This is grounded explanatory material, not a canonical relationship.","noncanonical-note"),el("p",x.statement));const dl=el("dl",undefined,"detail-grid");[["Participants",x.participant_entity_ids.join(", ")],["Presentation role",x.presentation_role],["Direction","None"]].forEach(([a,b])=>dl.append(el("dt",a),el("dd",b)));d.append(dl);addEvidence(d,x.evidence,true)}
function attention(){document.querySelectorAll(".projection-node,.explanation-anchor,.projection-canonical,.projection-canonical-label,.projection-attachment").forEach(n=>n.classList.remove("is-selected","is-unrelated"));document.querySelectorAll(".nav-node").forEach(n=>n.classList.toggle("is-unrelated",Boolean(S.selected)&&S.selected.kind==="concept"&&n.dataset.entityId!==S.selected.id));if(S.level!=="PROJECTION"||!S.selected)return;const p=proj(),keep=new Set();if(S.selected.kind==="concept"){keep.add(S.selected.id);p.canonical_items.filter(x=>x.source_entity_id===S.selected.id||x.target_entity_id===S.selected.id).forEach(x=>{keep.add(x.id);keep.add(x.source_entity_id);keep.add(x.target_entity_id)});p.explanatory_items.filter(x=>x.participant_entity_ids.includes(S.selected.id)).forEach(x=>{keep.add(x.id);x.participant_entity_ids.forEach(v=>keep.add(v))})}else if(S.selected.kind==="canonical"){const x=p.canonical_items.find(x=>x.id===S.selected.id);[x.id,x.source_entity_id,x.target_entity_id].forEach(v=>keep.add(v))}else{const x=p.explanatory_items.find(x=>x.id===S.selected.id);keep.add(x.id);x.participant_entity_ids.forEach(v=>keep.add(v))}document.querySelectorAll("[data-item-id],[data-entity-id]").forEach(n=>{const id=n.dataset.itemId||n.dataset.entityId;n.classList.toggle("is-selected",id===S.selected.id);n.classList.toggle("is-unrelated",!keep.has(id))})}
function renderNav(){const svg=$("nav-graph");svg.replaceChildren();markers(svg);const region=S.fixture.domains[0].world_region;svg.append(se("rect",{class:"domain-region",x:region.x,y:region.y,width:region.width,height:region.height,rx:18}));const title=se("text",{class:"domain-region-label",x:100,y:120});title.textContent="QUANTUM MECHANICS";svg.append(title);const routes=new Map(S.fixture.navigation.world.routes.map(r=>[r.edge_key,r]));S.fixture.navigation.edges.forEach(e=>{const r=routes.get(e.edge_key),d=routePath(r),line=se("path",{d,class:"nav-edge-line","data-nav-edge":""});line.style.markerEnd="url(#nav-arrow)";svg.append(line)});S.fixture.navigation.nodes.forEach(n=>{const g=se("g",{class:`nav-node${n.has_deeper_resolution?" has-depth":""}`,tabindex:0,role:"button","aria-label":n.has_deeper_resolution?`${n.label}, deeper resolution available`:n.label,"data-entity-id":n.entity_id});g.append(se("rect",{x:n.world.x-84,y:n.world.y-30,width:168,height:60,rx:8}));const t=se("text",{x:n.world.x,y:n.world.y+4,"text-anchor":"middle"});t.textContent=n.label.length>24?`${n.label.slice(0,22)}…`:n.label;g.append(t);if(n.has_deeper_resolution){const plus=se("text",{x:n.world.x+70,y:n.world.y-13,class:"depth-indicator"});plus.textContent="+";g.append(plus)}g.addEventListener("click",()=>{if(n.entity_id!==S.fixture.semantic_depth.focus_entity_id)S.level="PARENT";select("concept",n.entity_id);renderLearning()});g.addEventListener("keydown",e=>activate(e,()=>select("concept",n.entity_id)));svg.append(g)});viewbox()}
function renderParent(svg){const r=pRep();svg.setAttribute("viewBox",`0 0 ${r.layout.width} ${r.layout.height}`);markers(svg);const routes=new Map(r.layout.edges.map(x=>[x.edge_key,x]));r.edges.forEach(e=>{const q=routes.get(e.edge_key),id=e.relationship_ids[0],d=routePath(q),line=se("path",{d,class:"learn-edge-line"}),hit=se("path",{d,class:"learn-edge-hit",tabindex:0,role:"button","aria-label":e.relationship_label});hit.addEventListener("click",()=>select("relationship",id));hit.addEventListener("keydown",x=>activate(x,()=>select("relationship",id)));svg.append(line,hit)});const pos=new Map(r.layout.nodes.map(x=>[x.entity_id,x]));r.nodes.forEach(n=>{const p=pos.get(n.entity_id),g=se("g",{class:"learn-node",tabindex:0,role:"button","data-entity-id":n.entity_id});g.append(se("rect",{x:p.x-84,y:p.y-30,width:168,height:60,rx:8}));const t=se("text",{x:p.x,y:p.y+4,"text-anchor":"middle"});t.textContent=n.label;g.append(t);g.addEventListener("click",()=>select("concept",n.entity_id));g.addEventListener("keydown",e=>activate(e,()=>select("concept",n.entity_id)));svg.append(g)})}
function renderProjection(svg){const p=proj(),L=p.layout;svg.setAttribute("viewBox",`0 0 ${L.width} ${L.height}`);markers(svg);L.explanatory_attachments.forEach(a=>{const d=`M${a.from.x} ${a.from.y}L${a.to.x} ${a.to.y}`,line=se("path",{d,class:"projection-attachment","data-item-id":a.explanatory_item_id}),hit=se("path",{d,class:"projection-attachment-hit","data-item-id":a.explanatory_item_id});hit.addEventListener("click",()=>select("explanation",a.explanatory_item_id));svg.append(line,hit)});p.canonical_items.forEach(x=>{const r=L.canonical_edges.find(e=>e.canonical_item_id===x.id),d=`M${r.from.x} ${r.from.y}L${r.to.x} ${r.to.y}`,line=se("path",{d,class:"projection-canonical","data-item-id":x.id}),hit=se("path",{d,class:"projection-canonical-hit",tabindex:0,role:"button","aria-label":`${x.relationship_type} trusted canonical relationship`,"data-item-id":x.id}),label=se("text",{x:(r.from.x+r.to.x)/2,y:(r.from.y+r.to.y)/2-9,"text-anchor":"middle",class:"projection-canonical-label","data-item-id":x.id});label.textContent=x.relationship_type.replaceAll("_"," ");hit.addEventListener("click",()=>select("canonical",x.id));hit.addEventListener("keydown",e=>activate(e,()=>select("canonical",x.id)));svg.append(line,hit,label)});p.concepts.forEach(n=>{const q=L.concept_positions[n.entity_id],g=se("g",{class:`learn-node projection-node${n.is_focus?" focus":""}`,tabindex:0,role:"button","aria-label":n.is_focus?`${n.label}, current focus`:n.label,"data-entity-id":n.entity_id});g.append(se("rect",{x:q.x-84,y:q.y-30,width:168,height:60,rx:8}));const t=se("text",{x:q.x,y:q.y+4,"text-anchor":"middle"});t.textContent=n.label;g.append(t);if(n.is_focus){const c=se("text",{x:q.x,y:q.y-40,"text-anchor":"middle",class:"focus-caption"});c.textContent="CURRENT FOCUS";g.append(c)}g.addEventListener("click",()=>select("concept",n.entity_id));g.addEventListener("keydown",e=>activate(e,()=>select("concept",n.entity_id)));svg.append(g)});p.explanatory_items.forEach(x=>{const q=L.explanatory_anchors.find(a=>a.explanatory_item_id===x.id),g=se("g",{class:"explanation-anchor",tabindex:0,role:"button","aria-label":`${x.short_label}, source-backed non-canonical explanation`,"data-item-id":x.id});g.append(se("rect",{x:q.x-65,y:q.y-19,width:130,height:38,rx:19}));const t=se("text",{x:q.x,y:q.y+4,"text-anchor":"middle"});t.textContent=x.short_label;g.append(t);g.addEventListener("click",()=>select("explanation",x.id));g.addEventListener("keydown",e=>activate(e,()=>select("explanation",x.id)));svg.append(g)})}
function renderLearning(){context();const svg=$("learning-graph");svg.replaceChildren();const deeper=S.level==="PROJECTION";$("learning-title").textContent=deeper?"Double-slit experiment · deeper":"Double-slit experiment";$("representation-badge").textContent=deeper?"EXPLANATORY":"HIGH";$("representation-meta").replaceChildren(document.createTextNode(deeper?"7 concepts · 2 canonical relationships · 6 source-backed explanations":"Trusted parent focus relationship"));if(deeper){const key=el("span",undefined,"tier-key");key.innerHTML='<span><i></i>Trusted canonical</span><span class="weak"><i></i>Source-backed explanation</span>';$("representation-meta").append(key);renderProjection(svg)}else renderParent(svg);attention();detail()}
function installMap(){const v=$("nav-viewport"),svg=$("nav-graph");v.addEventListener("pointerdown",e=>{if(e.target!==v&&e.target!==svg)return;S.pan={id:e.pointerId,x:e.clientX,y:e.clientY,camera:{...S.camera}};v.setPointerCapture(e.pointerId);v.classList.add("is-panning")});v.addEventListener("pointermove",e=>{if(!S.pan||S.pan.id!==e.pointerId)return;const r=v.getBoundingClientRect(),s=viewSize(),dx=e.clientX-S.pan.x,dy=e.clientY-S.pan.y;S.pan.x=e.clientX;S.pan.y=e.clientY;S.camera=clamp({x:S.camera.x-dx*s.width/r.width,y:S.camera.y-dy*s.height/r.height,scale:S.camera.scale});viewbox()});const done=e=>{if(!S.pan||S.pan.id!==e.pointerId)return;if(!same(S.pan.camera,S.camera)){S.back.push(S.pan.camera);S.forward=[]}S.pan=null;v.classList.remove("is-panning");buttons()};v.addEventListener("pointerup",done);v.addEventListener("wheel",e=>{e.preventDefault();const r=v.getBoundingClientRect(),vp=S.fixture.navigation.camera.viewport,a={x:(e.clientX-r.left)*vp.width/r.width,y:(e.clientY-r.top)*vp.height/r.height},world={x:S.camera.x+a.x/S.camera.scale,y:S.camera.y+a.y/S.camera.scale},scale=S.camera.scale*Math.exp(-e.deltaY*.0015);setCamera({x:world.x-a.x/scale,y:world.y-a.y/scale,scale})},{passive:false});const zoom=f=>{const vp=S.fixture.navigation.camera.viewport,a={x:vp.width/2,y:vp.height/2},world={x:S.camera.x+a.x/S.camera.scale,y:S.camera.y+a.y/S.camera.scale},scale=S.camera.scale*f;setCamera({x:world.x-a.x/scale,y:world.y-a.y/scale,scale})};$("zoom-in").onclick=()=>zoom(1.25);$("zoom-out").onclick=()=>zoom(.8);$("overview").onclick=()=>setCamera({...S.fixture.navigation.camera.initial});$("history-back").onclick=()=>{if(!S.back.length)return;S.forward.push({...S.camera});S.camera=S.back.pop();viewbox()};$("history-forward").onclick=()=>{if(!S.forward.length)return;S.back.push({...S.camera});S.camera=S.forward.pop();viewbox()}}
fetch("workspace-manifest.json").then(r=>r.json()).then(m=>fetch(m.workspace_fixture)).then(r=>r.json()).then(f=>{S.fixture=f;S.camera={...f.navigation.camera.initial};S.selected={kind:"concept",id:f.semantic_depth.focus_entity_id};renderNav();renderLearning();installMap();$("depth-toggle").onclick=toggle;$("clear-selection").onclick=clear;buttons()}).catch(e=>{$("learning-title").textContent="Workspace data could not be loaded";$("learning-detail").textContent=String(e)});
