"use strict";

const state={packet:null,index:0,mode:"R0",selectedUnit:null,errors:[],warnings:[]};
const byId=id=>document.getElementById(id);
const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const current=()=>state.packet.cases[state.index];

function showDefaultAudit(){const item=current();byId("audit-title").textContent="Recoverable by construction";byId("audit-body").textContent=`${item.provenance_recoverability_audit.unit_count} essential units; 100% retain exact support, source identity, and admitted-model identity.`;byId("support-list").replaceChildren();}
function selectUnit(unit){state.selectedUnit=unit.id;byId("audit-title").textContent=unit.semantic_role.replaceAll("_"," ");byId("audit-body").textContent=unit.concise_text;const host=byId("support-list");host.replaceChildren();unit.support.forEach(support=>{host.append(el("blockquote",null,support.quote));host.append(el("p",null,`${support.source_id} · ${support.document_id} · chars ${support.start_char}–${support.end_char} · model ${support.model_sha256.slice(0,12)}…`));});}
function renderProse(host,text,className){const p=el("p",`prose-view ${className}`,text);p.dataset.viewText=text;host.append(p);}
function renderUnits(host,item){const list=el("ol","unit-list");item.essential_information_model.units.forEach(unit=>{const row=el("li"),button=el("button");button.type="button";button.dataset.unitId=unit.id;button.append(el("span","unit-role",unit.semantic_role.replaceAll("_"," ")));button.append(el("span","unit-text",unit.concise_text));button.addEventListener("click",()=>selectUnit(unit));row.append(button);list.append(row);});host.append(list);}
function renderAudit(host,item){const semantic=item.semantic_preservation_audit,epistemic=item.epistemic_preservation_audit,provenance=item.provenance_recoverability_audit;[["SEMANTIC PRESERVATION",`${semantic.required_item_count} required items · ${semantic.material_omission_count} material omissions · ${semantic.semantic_change_count} semantic changes`],["EPISTEMIC FIDELITY",`${epistemic.units_with_explicit_qualification_links} qualified units · ${epistemic.strengthened_certainty_or_causality_count} strengthened certainty/causality`],["RECOVERABILITY",`${provenance.units_with_support}/${provenance.unit_count} units supported · ${(provenance.coverage_ratio*100).toFixed(0)}% provenance coverage`],["INDEPENDENT GENERATION","R0, R1, and R2 each derive directly from the frozen grounded substrate; no compressed view feeds another."]].forEach(([title,text])=>{const card=el("div","audit-card");card.append(el("strong",null,title));card.append(el("p",null,text));host.append(card);});}
function renderMetrics(item){const host=byId("metric-strip"),metrics=item.essential_information_model.compression_metrics;host.replaceChildren();[["R0",metrics.r0.words,"100%"],["R1",metrics.r1.words,`${Math.round(metrics.r1_to_r0_word_ratio*100)}% of R0`],["R2",metrics.r2.words,`${Math.round(metrics.r2_to_r0_word_ratio*100)}% of R0`]].forEach(([label,words,ratio])=>{const card=el("div","metric");card.append(el("strong",null,String(words)));card.append(document.createTextNode(`${label} words · ${ratio}`));host.append(card);});}
function renderResolution(){const item=current(),host=byId("resolution-host");host.replaceChildren();host.dataset.caseIdentity=item.case_identity;host.dataset.mode=state.mode;["R0","R1","R2","AUDIT"].forEach(mode=>byId(`mode-${mode.toLowerCase()}`).setAttribute("aria-pressed",String(state.mode===mode)));if(state.mode==="R0"){byId("resolution-label").textContent="R0 · SOURCE RICH";renderProse(host,item.views.R0.text,"source-rich");}else if(state.mode==="R1"){byId("resolution-label").textContent="R1 · ESSENTIAL EXPLANATION";renderProse(host,item.views.R1.text,"essential-explanation");}else if(state.mode==="R2"){byId("resolution-label").textContent="R2 · ESSENTIAL UNITS";renderUnits(host,item);}else{byId("resolution-label").textContent="PRESERVATION + PROVENANCE AUDIT";renderAudit(host,item);}renderMetrics(item);state.selectedUnit=null;showDefaultAudit();}
function renderCase(){const item=current();byId("case-counter").textContent=`CASE ${item.review_index} OF ${state.packet.cases.length}`;byId("case-title").textContent=item.source_identity.title;byId("case-domain").textContent=`${item.source_identity.domain} · ${item.source_identity.institutional_publisher}`;[...byId("case-list").querySelectorAll("button")].forEach((button,index)=>button.setAttribute("aria-current",String(index===state.index)));renderResolution();}
function selectCase(index){state.index=(index+state.packet.cases.length)%state.packet.cases.length;state.mode="R0";renderCase();}
function setMode(mode){if(!["R0","R1","R2","AUDIT"].includes(mode))throw new Error(`Unknown mode ${mode}`);state.mode=mode;renderResolution();}
function nextCase(){selectCase(state.index+1);}function previousCase(){selectCase(state.index-1);}
function installCases(){const host=byId("case-list");state.packet.cases.forEach((item,index)=>{const row=el("li"),button=el("button",null,item.source_identity.title);button.type="button";button.dataset.index=String(index+1).padStart(2,"0");button.dataset.caseIdentity=item.case_identity;button.addEventListener("click",()=>selectCase(index));row.append(button);host.append(row);});}
function snapshot(){const item=current(),host=byId("resolution-host"),prose=host.querySelector(".prose-view"),units=[...host.querySelectorAll("[data-unit-id]")];return {case_identity:item.case_identity,mode:state.mode,host_case_identity:host.dataset.caseIdentity,text:prose?.dataset.viewText||null,unit_ids:units.map(node=>node.dataset.unitId),audit_cards:host.querySelectorAll(".audit-card").length,selected_unit:state.selectedUnit};}
function machineGate(){const start={index:state.index,mode:state.mode},rows=[];for(let index=0;index<state.packet.cases.length;index++){selectCase(index);const item=current();setMode("R0");const r0=snapshot();setMode("R1");const r1=snapshot();setMode("R2");const r2=snapshot(),firstUnit=byId("resolution-host").querySelector("[data-unit-id]");if(firstUnit)firstUnit.click();const selected=snapshot();setMode("AUDIT");const audit=snapshot(),resolutionHost=byId("resolution-host");rows.push({case_identity:item.case_identity,r0_identity_exact:r0.case_identity===r0.host_case_identity,r1_identity_exact:r1.case_identity===r1.host_case_identity,r2_identity_exact:r2.case_identity===r2.host_case_identity,r0_text_exact:r0.text===item.views.R0.text,r1_text_exact:r1.text===item.views.R1.text,r2_units_exact:JSON.stringify(r2.unit_ids)===JSON.stringify(item.views.R2.unit_ids),r2_text_independently_recorded:item.views.R2.depends_on.length===0&&item.views.R2.direct_input==="FROZEN_ADMITTED_SEMANTIC_ITEMS_AND_EVIDENCE",r1_text_independently_recorded:item.views.R1.depends_on.length===0&&item.views.R1.direct_input==="FROZEN_SOURCE_TEXT_AND_REQUIRED_EVIDENCE_RANGES",trace_selection_works:selected.selected_unit===item.views.R2.unit_ids[0],audit_visible:audit.audit_cards===4,no_visualization_dom:resolutionHost.querySelectorAll("svg,canvas,.diagram,.chart").length===0});}selectCase(start.index);setMode(start.mode);return {case_count:state.packet.cases.length,all_cases_pass:rows.every(row=>Object.entries(row).filter(([key])=>key!=="case_identity").every(([,value])=>value===true)),rows,errors:[...state.errors],warnings:[...state.warnings]};}

async function install(){try{const [packet,rubric]=await Promise.all([fetch("cases.json").then(response=>response.json()),fetch("owner-review-rubric.json").then(response=>response.json())]);state.packet=packet;installCases();rubric.criteria.forEach(item=>byId("rubric-list").append(el("li",null,`${item.label} — ${item.question}`)));byId("previous-case").addEventListener("click",previousCase);byId("next-case").addEventListener("click",nextCase);["R0","R1","R2","AUDIT"].forEach(mode=>byId(`mode-${mode.toLowerCase()}`).addEventListener("click",()=>setMode(mode)));renderCase();window.__SPEC060_REVIEW__={snapshot,selectCase,setMode,nextCase,previousCase,machineGate,state};const contract=byId("spec060-contract"),gate=machineGate();contract.dataset.browserGate=JSON.stringify(gate);contract.dataset.browserReady="true";document.dispatchEvent(new CustomEvent("spec060-review-ready"));}catch(error){state.errors.push(String(error));document.body.dataset.loadError=String(error);throw error;}}
window.addEventListener("error",event=>state.errors.push(event.message));window.addEventListener("unhandledrejection",event=>state.errors.push(String(event.reason)));install();
