"use strict";

// SPEC-035: representations may own local inspection state, but only My Map and
// Explore Next may dispatch authoritative navigation.
const purificationState={contextKey:null,highlightedKey:null,interactionCount:0,scheduled:false};
const purificationAtomicAttributes=["data-atomic-id","data-atomic-kind","data-atomic-ancestry","data-atomic-surface","data-atomic-domain","data-atomic-representation-index","data-learning-semantic"];
function purificationFocus(){const state=window.__SPEC029_ATOMIC__.snapshot(),kind=state.selected?state.selected.kind:"orientation",identity=state.selected?.identity||`domain:${state.activeContext.domainId}`;return{contextKey:document.getElementById("spec034-strategy-contract")?.dataset.contextKey||"PENDING",kind,identity};}
function purificationSameFocus(left,right){return left.contextKey===right.contextKey&&left.kind===right.kind&&left.identity===right.identity;}
function purificationMarker(){return document.getElementById("spec035-purification-contract");}
function purificationAudit(values={}){const marker=purificationMarker();if(!marker)return;const focus=purificationFocus(),host=document.getElementById("representation-strategy-host");marker.dataset.authoritativeFocusOwner="SPEC-029 atomicLearnerState";marker.dataset.localStateOwner="purificationState";marker.dataset.contextKey=purificationState.contextKey||focus.contextKey;marker.dataset.currentFocus=`${focus.kind}:${focus.identity}`;marker.dataset.localHighlightedKey=purificationState.highlightedKey||"NONE";marker.dataset.interactionCount=String(purificationState.interactionCount);marker.dataset.representationNavigationTargetCount=String(host?.querySelectorAll("[data-atomic-id],[data-learning-semantic]").length||0);marker.dataset.activeExploreDeeperCount=String([...document.querySelectorAll(".contextual-depth")].filter(node=>!node.hidden&&!node.disabled&&getComputedStyle(node).display!=="none").length);Object.entries(values).forEach(([key,value])=>marker.dataset[key]=String(value));}
function purificationDisableLegacyDepth(){document.querySelectorAll("#learning-detail .contextual-depth").forEach(button=>{button.hidden=true;button.disabled=true;button.tabIndex=-1;button.setAttribute("aria-hidden","true");button.dataset.spec035SupersededBy="explore-next";});document.querySelectorAll("#representation-strategy-host .contextual-depth").forEach(button=>button.remove());}
function purificationSanitizeHost(){const host=document.getElementById("representation-strategy-host"),contract=document.getElementById("spec034-strategy-contract");if(!host||!contract)return;const contextKey=contract.dataset.contextKey;if(contextKey&&contextKey!==purificationState.contextKey){purificationState.contextKey=contextKey;purificationState.highlightedKey=null;const marker=purificationMarker();if(marker){marker.dataset.focusBefore="NONE";marker.dataset.focusAfter="NONE";marker.dataset.navigationMutation="false";marker.dataset.lastLocalKey="NONE";marker.dataset.stateSeparation="NOT_TESTED_IN_THIS_CONTEXT";}}host.querySelectorAll("[data-atomic-id],[data-learning-semantic]").forEach(node=>{const identity=node.dataset.atomicId,kind=node.dataset.atomicKind||"component";if(identity)node.dataset.explanatoryLocalKey=`${kind}:${identity}`;node.dataset.explanatoryInteraction="local-only";purificationAtomicAttributes.forEach(name=>node.removeAttribute(name));if(node.matches("button")){node.setAttribute("aria-pressed",String(node.dataset.explanatoryLocalKey===purificationState.highlightedKey));node.title="Inspect within this explanation";}});host.querySelectorAll(".strategy-card").forEach(node=>node.classList.toggle("is-local-highlight",node.dataset.explanatoryLocalKey===purificationState.highlightedKey));purificationDisableLegacyDepth();purificationAudit();}
function purificationDepthFrontier(){const suggestions=document.querySelector("#exploration-suggestions .revealed-suggestion-list"),revealed=document.getElementById("spec033-revealed-contract"),current=revealed?.dataset.currentObjectKey,depth=window.__SPEC024_DEPTH__;if(!suggestions||!depth)return;const existing=suggestions.querySelector("[data-spec035-depth-frontier]");if(current!=="concept:double-slit-experiment"||revealed?.dataset.depthAdmitted==="true"||depth.isExpanded()){existing?.remove();return;}if(existing)return;const button=document.createElement("button"),basis=document.createElement("small");button.type="button";button.className="revealed-suggestion";button.dataset.spec035DepthFrontier="depth-double-slit-v1";button.append(document.createTextNode("Explore the double-slit model"));basis.textContent="Grounded deeper knowledge from the committed source";button.append(basis);button.addEventListener("click",event=>{event.preventDefault();event.stopImmediatePropagation();depth.expand({originEntityId:"double-slit-experiment"});});suggestions.prepend(button);}
function purificationSchedule(){if(purificationState.scheduled)return;purificationState.scheduled=true;requestAnimationFrame(()=>{purificationState.scheduled=false;purificationSanitizeHost();purificationDepthFrontier();});}
function purificationLocalInteraction(event){if(event.type==="keydown"&&!['Enter',' '].includes(event.key))return;const target=event.target.closest?.("#representation-strategy-host [data-explanatory-local-key]");if(!target)return;event.preventDefault();event.stopImmediatePropagation();const before=purificationFocus(),key=target.dataset.explanatoryLocalKey;purificationState.highlightedKey=purificationState.highlightedKey===key?null:key;purificationState.interactionCount+=1;purificationSanitizeHost();requestAnimationFrame(()=>{const after=purificationFocus(),same=purificationSameFocus(before,after);purificationAudit({focusBefore:`${before.kind}:${before.identity}`,focusAfter:`${after.kind}:${after.identity}`,navigationMutation:String(!same),lastLocalKey:key,stateSeparation:same?"PASS":"FAIL"});if(!same)console.error("SPEC-035 explanatory interaction mutated authoritative focus");});}
function purificationInstall(){if(!window.__SPEC034_STRATEGY__||!window.__SPEC033_REVEALED__||!window.__SPEC029_ATOMIC__||!document.getElementById("representation-strategy-host")){requestAnimationFrame(purificationInstall);return;}const marker=document.createElement("div");marker.id="spec035-purification-contract";marker.hidden=true;marker.dataset.navigationAuthority="MY_MAP_OR_EXPLORE_NEXT";marker.dataset.forwardAuthority="EXPLORE_NEXT_ONLY";marker.dataset.learningHistoryImplemented="false";document.body.append(marker);const host=document.getElementById("representation-strategy-host");host.addEventListener("click",purificationLocalInteraction,true);host.addEventListener("keydown",purificationLocalInteraction,true);new MutationObserver(purificationSchedule).observe(host,{childList:true,subtree:true});new MutationObserver(purificationSchedule).observe(document.getElementById("learning-detail"),{childList:true});new MutationObserver(purificationSchedule).observe(document.getElementById("exploration-suggestions"),{childList:true,subtree:true});new MutationObserver(purificationSchedule).observe(document.getElementById("spec034-strategy-contract"),{attributes:true});new MutationObserver(purificationSchedule).observe(document.getElementById("spec033-revealed-contract"),{attributes:true});purificationSchedule();document.dispatchEvent(new CustomEvent("spec035-purification-ready"));}
purificationInstall();
window.__SPEC035_PURIFICATION__={state:()=>({...purificationState}),focus:purificationFocus,sanitize:purificationSanitizeHost,contract:()=>{const marker=purificationMarker();return marker?{...marker.dataset}:null;}};
