"""Source-blind BENCH-001 artifact freezer. No source loading or execution."""
from __future__ import annotations
import argparse
import hashlib
import io
import json
from importlib.metadata import version
from pathlib import Path
import subprocess
import sys
import tarfile

import bench001_harness as h
from knowledge_compiler.openai_extractor import build_instructions, extraction_schema
from knowledge_compiler.openai_decomposed_extractor import build_entity_inventory_instructions, entity_inventory_schema, claim_evidence_schema
from knowledge_compiler.openai_decomposed_extractor_v2 import build_stage2_v2_instructions, build_stage3_v2_instructions, stage2_v2_schema
from knowledge_compiler.decomposed_extraction import freeze_entity_inventory
from knowledge_compiler.models import SourceDocument

ROOT = Path(__file__).resolve().parents[1]
OUT = Path("audits/independent-architecture-audit-001/benchmark-readiness-v1")
REF = "7b83d8d4361d02dfbe1c8b5c0a7ae0d79fd4758a"
CONTRACT = "specs/BENCH-001-ia001-benchmark-execution-readiness.md"
SEED = "c3c2c7e149fdc2cd3a30ac03ed74866fefc5ea48ad8d6a822a628bf6d72e43b1"

def stable(value):
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode()

def identity(root, path):
    data = (root / path).read_bytes()
    return {"path": path, "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)}

def protected(root):
    archive = subprocess.check_output(["git", "archive", REF], cwd=root)
    rows = []
    with tarfile.open(fileobj=io.BytesIO(archive)) as t:
        for m in t.getmembers():
            if not m.isfile() or m.name in {"STATUS.md", CONTRACT}:
                continue
            data = t.extractfile(m).read()
            if (root / m.name).read_bytes() != data:
                raise ValueError("protected historical file drift: " + m.name)
            rows.append({"path": m.name, "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)})
    return {"freeze_commit": REF, "files": sorted(rows, key=lambda r: r["path"])}

def build(root=ROOT):
    # Contract text at the input commit is authoritative transcription. Status
    # closure is not permission to edit its experiment rules.
    original = subprocess.check_output(["git", "show", f"{REF}:{CONTRACT}"], cwd=root)
    current = (root / CONTRACT).read_bytes()
    if current.replace(b"Status: `IMPLEMENTED_AWAITING_REVIEW`", b"Status: `APPROVED_FOR_IMPLEMENTATION`", 1) != original:
        raise ValueError("frozen benchmark rule drift")
    result = {"IA-001-BENCH-v1-frozen-contract.md": original}
    prompts = {**h.PROMPTS, "C0": build_instructions(), "C+-inventory": build_entity_inventory_instructions(),
               "C+-structure": build_stage2_v2_instructions(), "C+-bindings": build_stage3_v2_instructions()}
    # Dynamic IDs are generated by frozen schema factories, never inferred or
    # tuned from benchmark content. Template is synthetic and not transmitted.
    inventory = freeze_entity_inventory({"symbols": [
        {"name": "template process", "description": "Template identity.", "entity_type": "PROCESS", "aliases": []},
        {"name": "template object", "description": "Template identity.", "entity_type": "OBJECT", "aliases": []}]},
        SourceDocument("synthetic-schema-template", "Template only; no benchmark source."))
    schemas = {"A": h.envelope_schema(), "B-plan": h.plan_schema(), "B-compose": h.envelope_schema(),
               "C0": extraction_schema(), "C+-inventory": entity_inventory_schema(),
               "C+-structure-template": stage2_v2_schema(inventory),
               "C+-bindings-template": claim_evidence_schema(frozenset({"template-semantic-id"})),
               "C+-compose": h.envelope_schema()}
    for name, text in prompts.items():
        result["prompts/" + name + ".txt"] = (text + "\n").encode()
    for name, schema in schemas.items():
        result["schemas/" + name + ".json"] = stable(schema)
    result["schema-instantiation-contract.json"] = stable({
        "structure_factory": "knowledge_compiler.openai_decomposed_extractor_v2.stage2_v2_schema",
        "bindings_factory": "knowledge_compiler.openai_decomposed_extractor.claim_evidence_schema",
        "dynamic_parameters": ["exact admitted frozen entity IDs/types", "exact frozen semantic object IDs"],
        "not_prompt_tuning": "Only enum identities/empty-array constraints bind mechanically to upstream admitted artifacts. Factory bytes and all semantic predicates/rules are frozen.",
        "templates_are_not_requests": True})
    result["common-model-manifest.json"] = stable({"model": h.MODEL, "reasoning": {"effort": "high"},
        "store": False, "sdk_max_retries": 0, "semantic_retries": 0, "repair_calls": 0,
        "sampling_parameters": {}, "model_seed": None, "seed_support": "UNVERIFIED_NO_UNSUPPORTED_PARAMETER_SENT",
        "initial_native_adapter_classification": "COMMON_MODEL_CONTRACT_REQUIRES_BOUNDED_ADAPTER_CHANGE",
        "after_isolated_plumbing_adapter": "COMMON_MODEL_CONTRACT_READY",
        "remote_support": "PROVIDER_REMOTE_SUPPORT_UNVERIFIED",
        "local_sdk_version": version("openai"), "request_shape_only": True,
        "mutation_seam": "BudgetClient replaces only model/reasoning/store/max_output_tokens/timeout. C0 extraction prompts/schema/normalization/dedup/model/coverage/routing remain native.",
        "future_hard_preconditions": ["owner-approved live control-plane packet", "five-source identity freeze", "hidden independent fidelity keys", "remote common-model contract verification", "frozen executable identity verification", "certified exact-input token counter", "zero-retry timeout-respecting transport", "independent pre-exposure custodian secret commitment"]})
    result["budget-contract.json"] = stable({"total_input_plus_output_per_arm_source": 32000,
        "generated_output_per_arm_source": 12000, "per_call_seconds": 300, "per_arm_source_seconds": 900,
        "allocations": h.ALLOCATIONS, "max_calls_five_sources": 40, "sdk_retries": 0,
        "semantic_retries": 0, "hidden_retries": 0, "repairs": 0, "follow_ups": 0,
        "input_enforcement": "Require request-hash-bound certified exact token count before each transmission; refuse uncertified/missing counts. Reserve input+requested output inside remaining ceiling. Provider usage overrun/counter mismatch fails and short-circuits. No byte-count heuristic disguised as certification.",
        "timeout_enforcement": "Transport timeout=min(300,900-elapsed). Transport must enforce cancellation; post-response timing checked too. Timed-out response is preserved but never successful.",
        "usage_missing": "FAIL_CLOSED_NO_LATER_STAGE", "failed_cell_rerun": "FORBIDDEN"})
    result["source-anchor-contract.json"] = stable({"type": "EXACT_UNIQUE_QUOTES_TO_NORMALIZED_CHARACTER_RANGES",
        "normalization": "native CRLF/CR to LF and strip; original text independently retained unchanged",
        "anchors": ["document_id", "source_sha256", "start_char", "end_char", "quote"],
        "coverage": "Every learner-visible block/title/organizing idea/qualification/structure caption/cell requires support. Labels/arrows/groupings are claims, not decoration.",
        "semantic_entailment_certified": False, "fidelity_authority": "two independent source-defined keys and third adjudicator, not the harness/model",
        "recovery": "original_text/original_sha256 and normalized_text/normalized_sha256 stored independently for every cell"})
    frozen_text = original.decode()
    rule_text = frozen_text.split("## Frozen decision rule\n",1)[1].split("## Required outputs",1)[0].strip()
    result["decision-rules.json"] = stable({"version": h.VERSION, "source": CONTRACT,
        "exact_section_transcription": rule_text, "promotion": "NOT_AUTHORIZED",
        "automated_winner_assignment": False, "threshold_changes": False})
    result["failure-contract.json"] = stable({"denominator": "25 cells: five sources times S/A/B/C0/C+; never remove failed cells",
        "failure_states": ["missing", "rejected", "timeout", "malformed", "budget_exhausted", "missing_usage", "model_mismatch", "ungrounded_anchor", "unrenderable_current_plan"],
        "fallback_gain": 0, "both_fail": "NEITHER", "material_fidelity_failure": "NO_FIDELITY_ADJUSTED_WIN",
        "partial_artifacts": "retain raw responses/requests/usage/IDs/timing and rejected plans/models; no learner substitution",
        "semantic_review": "PENDING until independent human fidelity review; anchor checks are not entailment",
        "C0_limit": "Claims are preserved in model but not silently added to current entity/relationship/proposition focus routing. Unsupported renderer forms fail rather than fabricated summary."})
    result["future-40-call-ledger.json"] = stable({"version": h.VERSION, "execution_authorized": False,
        "provider_calls_started": 0, "source_transmissions": 0, "source_selection": None,
        "slots": [{"source_slot": s, "source_sha256": None, "arm": a, "stage": i+1,
                   "output_allocation": n, "status": "NOT_EXECUTED", "receipt": None}
                  for s in range(1,6) for a in h.ARMS for i,n in enumerate(h.ALLOCATIONS[a])]})
    result["sealed-metrics-ledger-template.json"] = stable({"visibility": "CUSTODIAN_ONLY_UNTIL_LEARNER_VERDICTS_LOCKED",
        "entries": [], "fields": ["source/arm/stage/attempt identity", "request/transmission/outcome", "prompt/schema/input hashes",
        "raw rejected/accepted response", "response/request ID", "tokens/input/output/cache/reasoning", "provider duration", "elapsed time",
        "retries/repairs/followups", "local check outcomes and minutes", "reviewer minutes", "implementation effort minutes",
        "provenance recovery", "receipt-backed dollars or null"], "provider_calls": 0, "learner_bundle_contains_metrics": False})
    result["custody-contract.json"] = stable({"version": h.VERSION, "frozen_seed": SEED, "identity_key": None,
        "assign_labels_only_after_outputs": True, "order": "hash-sort arms by frozen seed then five cyclic Latin rotations; every arm occupies every position once",
        "hash_entropy": "frozen public seed plus independent custodian-only 256-bit secret; commit secret SHA-256 before source exposure, keep secret outside repository/learner bundle; no real secret/identity assigned in readiness",
        "custodian_secret_commitment_sha256": None,
        "owner_is_selector_or_identity_keeper": False, "fidelity_keys_visible_to_generator": False,
        "reviewer_obligations": "record arm guesses/confidence and unavoidable clues including source-control familiarity and C0 renderer differences",
        "release": "identity key, system ledger and metrics remain custodian-only until signed learner verdict lock; comprehension grading blinded"})
    assets = root / "tools/bench001_assets"
    for p in sorted(assets.iterdir()):
        if p.is_file(): result["renderer/" + p.name] = p.read_bytes()
    for directory, file, stop, out in [
        ("representation_strategy_assets", "representation-strategy.js", "function strategyRender(){", "current-native-plan.js"),
        ("diagram_canvas_assets", "diagram-canvas.js", "function diagramSyncAttention(){", "current-native-diagram.js")]:
        raw = (root / "src/knowledge_compiler" / directory / file).read_text()
        if raw.count(stop) != 1: raise ValueError("native renderer seam drift")
        result["renderer/"+out] = raw[:raw.index(stop)].encode()
    for directory, file in [("representation_strategy_assets", "representation-strategy.css"), ("diagram_canvas_assets", "diagram-canvas.css")]:
        result["renderer/"+file] = (root/"src/knowledge_compiler"/directory/file).read_bytes()
    result["renderer/current-host.html"] = b"<!doctype html><html><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Learning view</title><link rel='stylesheet' href='representation-strategy.css'><link rel='stylesheet' href='diagram-canvas.css'><link rel='stylesheet' href='neutral.css'><body class='spec038-diagram-canvas'><main><div id='current'></div></main><script src='current-native-plan.js'></script><script src='current-native-diagram.js'></script><script src='c0-adapter.js'></script></body></html>\n"
    result["protected-state.json"] = stable(protected(root))
    code_files = [str(p.relative_to(root)) for p in sorted((root/"src/knowledge_compiler").rglob("*")) if p.is_file() and "__pycache__" not in p.parts]
    code_files += ["tools/bench001_harness.py", "tools/bench001_prepare.py", "tools/bench001_renderer_check.mjs", "tools/bench001_renderer_check.py", "tests/test_bench001.py", "pyproject.toml"]
    result["dependency-executable-manifest.json"] = stable({"freeze_commit": REF,
        "python": ".".join(map(str,sys.version_info[:3])), "openai": version("openai"),
        "production_modules": "unchanged native components; isolated harness under tools/",
        "dependencies_added": [], "files": [identity(root,p) for p in code_files],
        "provider_remote_support": "UNVERIFIED", "host_portability": "Python>=3.12 with frozen source identity and openai 2.54.0; no network install under readiness"})
    result["C0-executable-manifest.json"] = stable({"entry": "tools.bench001_harness.run_arm(C0)",
        "native_pipeline": ["normalize_document", "OpenAILLMExtractor", "deduplicate_entities", "KnowledgeModel", "validate_proposition_coverage", "StructureDetector", "compile_semantic_representation"],
        "extraction_prompt": "prompts/C0.txt", "extraction_schema": "schemas/C0.json",
        "renderer": "native strategyRenderPlan plus native diagramCanvas and native _layout_for_plan; frozen function slices byte-identical; no product fixture substitution",
        "chrome_changes": "surrounding navigation/workspace omitted for neutral benchmark reader; model/debug badges and evidence-ID paragraphs removed; source recovery kept",
        "confounders": ["C0 native diagram styling differs from A/B/C+ minimal envelope", "focus menu versus peer overview/detail", "local navigation shell omitted; this is not a re-review of the full SPEC-038 workspace", "missing claim foci and unsupported comparison renderer are retained, not rescued"],
        "reproducibility": "synthetic model and routing match unchanged native pipeline; native renderer bytes/geometry checked offline"})
    c0_manifest=json.loads(result["C0-executable-manifest.json"])
    c0_manifest["retained_semantic_limitations"] = ["Native extraction permits INFERRED outside-source knowledge; prompt is not rewritten for a source-bounded teaching task. Independent fidelity review must assess unsupported content.", "Entity descriptions and representation grouping remain the current compiler's semantics; exact anchors are not an entailment/completeness certificate."]
    result["C0-executable-manifest.json"] = stable(c0_manifest)
    result["Cplus-executable-manifest.json"] = stable({"entry": "tools.bench001_harness.run_arm(C+)",
        "extractor": "OpenAICandidateBV2Extractor", "admission": "run_candidate_b_v2 unchanged",
        "stages": ["typed inventory", "typed relationships/propositions", "exact claim/evidence bindings", "source-aware composer"],
        "composer_inputs": ["original source", "complete admitted entities/relationships/propositions/claims and evidence"],
        "semantic_store_completeness_assumed": False, "gate_weakening": False,
        "atomizer_or_semantic_judge": False, "production_promotion": False,
        "composer_envelope_schema": "schemas/C+-compose.json", "source_routing": "none", "live_outputs": 0})
    result["zero-call-zero-retrieval.txt"] = b"BENCH-001: zero provider/model calls, zero benchmark-source selection/retrieval/exposure, zero benchmark outputs, zero fidelity/learner reviews. Offline synthetic contract tests only. Git fetch/push are repository coordination, not benchmark network activity. No atomization/judge continuation, promotion or winner selection.\n"
    result["readiness-report.json"] = stable({"version": h.VERSION,
        "packet": CONTRACT, "status": "IMPLEMENTED_AWAITING_REVIEW",
        "mechanical_readiness_branch": "INCONCLUSIVE",
        "recommended_next_step": "MORE_READINESS_DIAGNOSIS",
        "owner_verdict": "PENDING", "human_gate": "OWNER_REVIEW", "promotion": "NOT_AUTHORIZED",
        "reason": "Full offline gate fails on a canonical pre-existing AUDIT-001 regeneration assertion: mutable STATUS.md was included in the historical dossier identity. BENCH-001 leaves the protected audit and upstream tests unchanged. No full-readiness claim is made.",
        "common_model": "COMMON_MODEL_CONTRACT_READY",
        "provider": "PROVIDER_REMOTE_SUPPORT_UNVERIFIED",
        "C0": "Executable on synthetic current pipeline with byte-identical native prompts/schemas, model/routing and native renderer functions; actual unsupported forms/claim-focus gaps remain failures or limits. No SPEC-038 fixtures substituted.",
        "Cplus": "Executable on synthetic inputs using unchanged Candidate B v2 admission plus isolated original-source-and-entire-store composer; no architecture change, judge or atomizer.",
        "future_dependencies": ["separately approved execution packet", "independent five-source freeze", "hidden pre-generation fidelity obligations/questions", "independent custody secret commitment before exposure", "remote model/high/store/structured-output verification", "certified exact-request token accounting and zero-retry cancellation-respecting transport"],
        "live_transmission_authorized": False, "sources_selected": 0, "benchmark_outputs": 0,
        "provider_model_calls": 0, "benchmark_network_calls": 0,
        "network_exception": "Only Git canonical fetch/push coordination; synthetic browser context offline and requests denied.",
        "validation": json.loads((root/OUT/"gate-results.json").read_bytes()),
        "freeze": {"input_commit": REF, "contract_sha256": hashlib.sha256(original).hexdigest(),
            "protected_file_count": len(json.loads(result["protected-state.json"])["files"]),
            "identities": "lock.json and dependency-executable-manifest.json; lock self-hash external to avoid cycle"},
        "handoffs": ["source-selector-handoff.md", "fidelity-review-handoff.md", "custodian-handoff.md",
                     "learner-review-handoff.md", "comprehension-grading-handoff.md"],
        "review_command": "open audits/independent-architecture-audit-001/benchmark-readiness-v1/README.md",
        "stopping_boundary": "Owner review only; no sources, candidate generation, future activation, promotion or benchmark winner."})
    # Human-authored contracts/templates are frozen with the generated outputs.
    manual = root / OUT
    templates = [p for p in sorted(manual.rglob("*")) if p.is_file() and (p.suffix == ".md" or p.parent.name == "templates" or p.name in {"gate-results.json", "full-offline-suite.txt"}) and p.name != "IA-001-BENCH-v1-frozen-contract.md"]
    manifest = {name: {"sha256": hashlib.sha256(raw).hexdigest(), "bytes": len(raw)} for name,raw in sorted(result.items())}
    manifest.update({str(p.relative_to(manual)): {"sha256": hashlib.sha256(p.read_bytes()).hexdigest(), "bytes": p.stat().st_size} for p in templates})
    result["lock.json"] = stable({"version": h.VERSION, "source_blind_freeze_commit": REF,
        "benchmark_contract_sha256": hashlib.sha256(original).hexdigest(),
        "source_content_seen_by_builders": False, "files": dict(sorted(manifest.items())),
        "excluded_self_hash": "lock.json self-hash computed externally; no hash cycle", "execute_now": False})
    return result

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument("--check",action="store_true");a=parser.parse_args()
    outputs=build()
    for name,raw in outputs.items():
        p=ROOT/OUT/name
        if a.check:
            if not p.is_file() or p.read_bytes()!=raw: raise ValueError("non-deterministic freeze: "+name)
        else:
            p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw)
    print(json.dumps({"result":"PASS","version":h.VERSION,"provider_calls":0,"retrieved_sources":0,"benchmark_outputs":0,"files":len(outputs),"owner_verdict":"PENDING"}))

if __name__=="__main__":main()
